const data = {
  products: [
    {
      name: 'Crop Top Shirt',
      slug: 'crop-top-shirt',
      category: 'Shirts',
      image: '/images/p1.jpeg',
      price: 50,
      countInStock: 25,
      brand: 'Skims',
      rating: 4.5,
      numReviews: 10,
      description: 'cute summer shirt',
    },
    {
      name: 'Ripped Jeans',
      slug: 'ripped-jeans',
      category: 'Bottoms',
      image: '/images/p2.webp',
      price: 100,
      countInStock: 50,
      brand: '7FAMK',
      rating: 4.9,
      numReviews: 15,
      description: 'distressed light jeans',
    },
    {
      name: 'Jogging Shorts',
      slug: 'jogging-shorts',
      category: 'Bottoms',
      image: '/images/p3.webp',
      price: 50,
      countInStock: 50,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 12,
      description: 'comfortable shorts',
    },
    {
      name: 'Skater Skirt',
      slug: 'skater-skirt',
      category: 'Bottoms',
      image: '/images/p4.jpeg',
      price: 25,
      countInStock: 25,
      brand: 'GIA',
      rating: 4.8,
      numReviews: 40,
      description: 'cute summer skirt',
    },
  ],
};
export default data;
